spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: test
    password: testdemo
  redis:
    timeout: 6000ms
    password:
    cluster:
      max-redirects: 3  # 获取失败 最大重定向次数
      nodes:
        - 10.10.50.15:6379
        - 10.10.50.16:6379
        - 10.10.50.17:6379
        - 10.10.50.18:6379
        - 10.10.50.19:6379
        - 10.10.50.20:6379
    lettuce:
      pool:
        max-active: 1000  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 30 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
  elasticsearch:
    uris: http://192.168.1.63:9200,http://192.168.1.43:9200,http://192.168.1.215:9200
    username: test
    password: AVX2EHVC#

app:
  appid: ac49ac
  appKey: 2a2ab

sync:
  sourceTable: basics_course_daily,basics_course_orga_daily